# CMake generated Testfile for 
# Source directory: /home/alexsmith/mr/drone/catkin_ws/src/interop
# Build directory: /home/alexsmith/mr/drone/catkin_ws/src/interop
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_interop_rostest_test_serializers.test "/home/alexsmith/mr/drone/catkin_ws/src/interop/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/alexsmith/mr/drone/catkin_ws/src/interop/test_results/interop/rostest-test_serializers.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/alexsmith/mr/drone/catkin_ws/src/interop --package=interop --results-filename test_serializers.xml --results-base-dir \"/home/alexsmith/mr/drone/catkin_ws/src/interop/test_results\" /home/alexsmith/mr/drone/catkin_ws/src/interop/test/serializers.test ")
add_test(_ctest_interop_rostest_test_client.test "/home/alexsmith/mr/drone/catkin_ws/src/interop/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/alexsmith/mr/drone/catkin_ws/src/interop/test_results/interop/rostest-test_client.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/alexsmith/mr/drone/catkin_ws/src/interop --package=interop --results-filename test_client.xml --results-base-dir \"/home/alexsmith/mr/drone/catkin_ws/src/interop/test_results\" /home/alexsmith/mr/drone/catkin_ws/src/interop/test/client.test ")
add_test(_ctest_interop_rostest_test_local_objects.test "/home/alexsmith/mr/drone/catkin_ws/src/interop/catkin_generated/env_cached.sh" "/usr/bin/python" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/alexsmith/mr/drone/catkin_ws/src/interop/test_results/interop/rostest-test_local_objects.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/alexsmith/mr/drone/catkin_ws/src/interop --package=interop --results-filename test_local_objects.xml --results-base-dir \"/home/alexsmith/mr/drone/catkin_ws/src/interop/test_results\" /home/alexsmith/mr/drone/catkin_ws/src/interop/test/local_objects.test ")
subdirs(gtest)
