set(_CATKIN_CURRENT_PACKAGE "interop")
set(interop_VERSION "0.15.0")
set(interop_MAINTAINER "Anass Al <mr@anassinator.com>")
set(interop_PACKAGE_FORMAT "1")
set(interop_BUILD_DEPENDS "rospy" "genmsg" "std_msgs" "geometry_msgs" "sensor_msgs" "geographic_msgs" "message_generation")
set(interop_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "message_runtime" "message_generation" "geographic_msgs" "python-numpy" "python-requests" "python-responses-pip" "python-dateutil" "python-imaging")
set(interop_BUILDTOOL_DEPENDS "catkin")
set(interop_BUILDTOOL_EXPORT_DEPENDS )
set(interop_EXEC_DEPENDS "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "message_runtime" "message_generation" "geographic_msgs" "python-numpy" "python-requests" "python-responses-pip" "python-dateutil" "python-imaging")
set(interop_RUN_DEPENDS "rospy" "std_msgs" "geometry_msgs" "sensor_msgs" "message_runtime" "message_generation" "geographic_msgs" "python-numpy" "python-requests" "python-responses-pip" "python-dateutil" "python-imaging")
set(interop_TEST_DEPENDS "rostest")
set(interop_DOC_DEPENDS )
set(interop_DEPRECATED "")