# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/Color.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/FlyZone.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/FlyZoneArray.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/GeoCylinder.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/GeoCylinderArrayStamped.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/GeoPolygon.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/GeoPolygonStamped.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/GeoSphere.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/GeoSphereArrayStamped.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/Object.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/ObjectType.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/Orientation.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/Shape.msg;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg/WayPoints.msg"
services_str = "/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/AddObject.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/DeleteObject.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/DeleteObjectImage.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/GetAllObjects.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/GetMissionByID.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/GetObject.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/GetObjectCompressedImage.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/GetObjectImage.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/SetObjectCompressedImage.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/SetObjectImage.srv;/home/alexsmith/mr/drone/catkin_ws/src/interop/srv/UpdateObject.srv"
pkg_name = "interop"
dependencies_str = "geographic_msgs;sensor_msgs;std_msgs;geometry_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "interop;/home/alexsmith/mr/drone/catkin_ws/src/interop/msg;geographic_msgs;/opt/ros/kinetic/share/geographic_msgs/cmake/../msg;sensor_msgs;/opt/ros/kinetic/share/sensor_msgs/cmake/../msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/kinetic/share/geometry_msgs/cmake/../msg;uuid_msgs;/opt/ros/kinetic/share/uuid_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = 'TRUE' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
